security:
  oauth2:
    client:
      clientId: uenta-statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD:password}
      accessTokenUri: http://192.168.0.164:8551/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 192.168.0.164
      username: user
      password: ${MONGODB_PASSWORD:password}
      database: piggymetrics
      port: 27000

server:
  context-path: /statistics
  port: 7000
  address: 0.0.0.0

rates:
  url: http://api.fixer.io
  
feign:
  hystrix:
    enabled: true
