spring:
#  rabbitmq:
#    host: 192.168.0.164
##    port: 15672
##    addresses: 
#    username: guest
#    password: guest
##    virtualhost: 
##    dynamic: 
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://192.168.0.164:${turbine.stream.port}

logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error

server:
  port: 7080
  address: 0.0.0.0

turbine:
  stream:
    port: 7081

#eureka:
#  instance:
#    hostname: 192.168.0.164
#    prefer-ip-address: true
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
#  client:
#    service-url:
#      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@192.168.0.164:7070/eureka/

security:
  user:
    name: user
    password: ${MONITOR_SERVER_PASSWORD:password}
