spring:
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME_EAST_1A:192.168.0.164}
#    port: 15672
#    addresses: 
    username: guest
    password: guest
#    virtualhost: 
#    dynamic: 
#  sleuth:
#    sampler:
#      percentage: 1
#    integration:
#      enabled: false
#    scheduled:
#      skip-pattern: "^org.*HystrixStreamTask$"

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000

eureka:
  instance:
    hostname: ${REGISTRY_HOSTNAME_EAST_1A:192.168.0.164}
    prefer-ip-address: true
#    health-check-url-path: ${server.context-path}${management.context-path}/health
#    status-page-url-path: ${server.context-path}${management.context-path}/info
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
#      management.context-path: ${server.context-path}${management.context-path}
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVER_USER:user}:${REGISTRY_SERVER_PASSWORD:password}@${REGISTRY_HOSTNAME_EAST_1A:192.168.0.164}:7000/eureka/

authserver:
  hostname: ${AUTH_HOSTNAME_EAST_1A:192.168.0.164}
  port: 7050
  contextPath: /uaa

security:
  oauth2:
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/users/current
#  user:
#    name: user
#    password: ${CONFIG_SERVER_PASSWORD:password}
