security:
  oauth2:
    client:
      clientId: uenta-statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD:password}
      accessTokenUri: http://${AUTH_HOSTNAME_EAST_1A:192.168.0.164}:7050/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ${MONGODB_STATISTICS_HOSTNAME:192.168.0.164}
      username: ${NOTIFICATION_SERVER_USER:user}
      password: ${NOTIFICATION_SERVER_PASSWORD:password}
      database: piggymetrics
      port: 27000

server:
  context-path: /statistics
  port: 7080
  address: 0.0.0.0

rates:
  url: http://api.fixer.io
  
feign:
  hystrix:
    enabled: true
