security:
  oauth2:
    client:
      clientId: uenta-account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD:password}
      accessTokenUri: http://192.168.0.164:8551/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 192.168.0.164
      username: user
      password: ${MONGODB_PASSWORD:password}
      database: piggymetrics
      port: 26000

server:
  context-path: /accounts
  port: 6000
  address: 0.0.0.0

feign:
  hystrix:
    enabled: true
